public with sharing class ALK_RMACalloutRequestWrapper {
    public String businessUnit = '';
	public String invoice = '';
	public String orderNo = '';
	public String custId = '';
	public String estReturnDt = '';
    public String reasonCd = '';    
    public String returnToIbu = '';
    public String oprid = '';
    public String oprid2 = '';
    public String carrierId = '';
    public String addressSeqNum = '';
    public String invItemId = '';
    public Decimal qty = 0;
    public String ckComments = '';
    public String rmaStatus = '';
    public String emailTo = '';
}